"""add soft delete to model order

Revision ID: 392aa57f58d7
Revises: 8234bfb8477a
Create Date: 2026-08-27 15:20:35.587242

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '392aa57f58d7'
down_revision = '8234bfb8477a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deleted_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_column('deleted_at')

    # ### end Alembic commands ###
