"""change order_items to association table

Revision ID: 758f48f675a8
Revises: c1a6bf80019c
Create Date: 2026-08-15 17:37:43.334201

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '758f48f675a8'
down_revision = 'c1a6bf80019c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order_items', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('order_items_quantity_check'), type_='check')
        batch_op.drop_column('quantity')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    with op.batch_alter_table('order_items', schema=None) as batch_op:
        batch_op.add_column(sa.Column('quantity', sa.INTEGER(), server_default=sa.text('1'), autoincrement=False, nullable=False))
        batch_op.create_check_constraint(batch_op.f('order_items_quantity_check'), 'quantity > 0')

    # ### end Alembic commands ###
